name: Test workflow

on:
  push:
    branches:
      - '*'

jobs:
  code-validation:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.18'

      - name: Install dependencies
        working-directory: ./github-tracker
        # Sincronizar dependencias
        run: go mod vendor

      - name: Run unit test
        working-directory: ./github-tracker
        # Todos los folders recursivamente
        run: go test ./...
        continue-on-error: false
